#!/bin/bash

for i in "$@"
do
case $i in
	-r=*)
	REF="${i#*=}"
	;;
	-f=*)
	READS="${i#*=}"
	;;
	-n=*)
	THREADS="${i#*=}"
	;;
	-h|--help)
	HELP=YES
	;;
esac
done
if [[ ! -z $HELP ]]; then 
	echo $'\n'"Usage: rnainigo -r=<reference> -f=<reads> [-n=Threads]"
	echo $'\n'"Result file will be located at WORKING_DIR/stat"
	echo $'\n'"WARNING please use the absolute PATH in the command"$'\n'
	exit 1
fi
if [[ -z $REF || -z $READS ]]; then
	echo $'\n'"Usage: rnainigo -r=<reference> -f=<reads> [-n=Threads]"
	echo $'\n'"Please provide <reference sequence> and <reads> in order to have the program work! Aborting!" 
	echo $'\n'"WARNING please use the absolute PATH in the command"$'\n'
	exit 1
else

if hash bwa 2>/dev/null; then
	echo "Processing ..."
	if [[ -z  $THREADS ]]; then
		bwa index ${REF}
		bwa mem -t 4 ${REF} ${READS}|countmap > stat
	else
		bwa index ${REF}
		bwa mem -t ${THREADS} ${REF} ${READS}|countmap > ${READS}.stat
	fi
else
	echo "Please install BWA 0.7+ to use mem method. Aborting!"
	exit 1
fi

fi

